/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import controller.ChiTietPhieuDatPhongController;
import controller.KhachHangController;
import controller.NhanVienController;
import controller.PhieuDatPhongController;
import controller.PhongController;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.ChiTietPhieuDatPhong;
import model.PhieuDatPhong;

/**
 *
 * @author ldlan
 */
public class fm_ChiTietDatPhong extends javax.swing.JFrame {

    public static int SophieuDatPhong;
    private ArrayList<ChiTietPhieuDatPhong> list;
    DefaultTableModel model;

    /**
     * Creates new form ChiTietDatPhong
     */
    public fm_ChiTietDatPhong() {
        initComponents();
        DesignTable(jTable1);
        showTable();
        PhieuDatPhong pdp = new PhieuDatPhongController().getPhieuDatPhong(SophieuDatPhong);
        lbSoPhieu.setText("Chi Tiết Thuê Phiếu "+SophieuDatPhong);
        lbNgayDat.setText(pdp.getNgayDatPhong().toString());
        String TenKhach = new KhachHangController().CheckCMND(pdp.getCMND());
        lbTenKhach.setText(TenKhach);
        String TenNhanVien = new NhanVienController().GetTenNhanVien(pdp.getMANV());
        lbNhanVien.setText(TenNhanVien);
    }

    public void showTable() {
        list = new ChiTietPhieuDatPhongController().getListChiTietPhieuDatPhongs(SophieuDatPhong);
        model = (DefaultTableModel) jTable1.getModel();
        String kh = "1232";

        model.getDataVector().removeAllElements();
        for (ChiTietPhieuDatPhong s : list) {

            kh = new PhongController().CheckTenPhong(s.getMaPhong());
            model.addRow(new Object[]{
                s.MaPhong, kh, s.GioVao, s.GioRa
            });

        }
    }

    void DesignTable(JTable jTable) {
        jTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable.getTableHeader().setOpaque(false);
        jTable.getTableHeader().setBackground(new Color(71, 127, 237));
        jTable.getTableHeader().setForeground(Color.BLACK);
        jTable.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnChucNang = new javax.swing.JPanel();
        lbSoPhieu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbTenKhach = new javax.swing.JLabel();
        lbNgayDat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbNhanVien = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(975, 629));

        pnChucNang.setBackground(new java.awt.Color(204, 204, 204));
        pnChucNang.setMinimumSize(new java.awt.Dimension(895, 100));
        pnChucNang.setPreferredSize(new java.awt.Dimension(738, 130));
        pnChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSoPhieu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbSoPhieu.setText("Chi Tiết Thuê Phiếu");
        pnChucNang.add(lbSoPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 290, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Close_16px_1.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        pnChucNang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 40, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_calendar_40px.png"))); // NOI18N
        pnChucNang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 40, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_user_48px_1.png"))); // NOI18N
        pnChucNang.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 40, 40));

        lbTenKhach.setText("1");
        pnChucNang.add(lbTenKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 50, -1));

        lbNgayDat.setText("1");
        pnChucNang.add(lbNgayDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 60, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_user_40px.png"))); // NOI18N
        pnChucNang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 40, 40));

        lbNhanVien.setText("1");
        pnChucNang.add(lbNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 60, -1));

        getContentPane().add(pnChucNang, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 1000));
        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 1000));
        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 20));
        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Ngày Bắt Đầu", "Ngày Kết Thúc"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(100);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(1).setMinWidth(150);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(150);
        }

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(912, 614));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fm_ChiTietDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fm_ChiTietDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fm_ChiTietDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fm_ChiTietDatPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fm_ChiTietDatPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbNgayDat;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbSoPhieu;
    private javax.swing.JLabel lbTenKhach;
    private javax.swing.JPanel pnChucNang;
    // End of variables declaration//GEN-END:variables
}
