/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import controller.KhachHangController;
import controller.PhieuDatPhongController;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.PhieuDatPhong;

/**
 *
 * @author ldlan
 */
public final class fm_DatPhong extends javax.swing.JPanel {

    private ArrayList<PhieuDatPhong> list;
    DefaultTableModel model;

    /**
     * Creates new form DatPhong1
     */
    public fm_DatPhong() {
        initComponents();
        DesignTable(jTable2);
        showTable();
    }

    void DesignTable(JTable jTable) {
        jTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable.getTableHeader().setOpaque(false);
        jTable.getTableHeader().setBackground(new Color(71, 127, 237));
        jTable.getTableHeader().setForeground(Color.BLACK);
        jTable.setRowHeight(25);
    }

    public void showTable() {
        list = new PhieuDatPhongController().getListPhieuDatPhongs();
        model = (DefaultTableModel) jTable2.getModel();
        String kh = "1232";

        model.getDataVector().removeAllElements();
        for (PhieuDatPhong s : list) {

            kh = new KhachHangController().CheckCMND(s.getCMND());
            model.addRow(new Object[]{
                s.getSoPhieuDatPhong(), s.getNgayDatPhong(), kh
            });

        }
    }
//   DatPhongMoi dpm = new DatPhongMoi();
//        dpm.setVisible(true);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnChucNang = new javax.swing.JPanel();
        btThemMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnChucNang.setBackground(new java.awt.Color(204, 255, 204));
        pnChucNang.setMinimumSize(new java.awt.Dimension(895, 100));
        pnChucNang.setPreferredSize(new java.awt.Dimension(738, 100));
        pnChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btThemMoi.setBackground(new java.awt.Color(0, 153, 102));
        btThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btThemMoi.setForeground(new java.awt.Color(255, 255, 255));
        btThemMoi.setText("Đặt Phòng Mới");
        btThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemMoiActionPerformed(evt);
            }
        });
        pnChucNang.add(btThemMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 185, 63));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Đặt Phòng");
        pnChucNang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(pnChucNang, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 1000));
        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 1000));
        add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 20));
        add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số Phiếu Đặt Phòng", "Ngày Đặt Phòng", "Người Đặt phòng "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setName(""); // NOI18N
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(245, 75, 97));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

//
    private void btThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemMoiActionPerformed
        fm_DatPhongMoi dpm = new fm_DatPhongMoi(this);
        dpm.setVisible(true);
    }//GEN-LAST:event_btThemMoiActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        int selectedIndex;
        selectedIndex = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        int SoPhieuDatPhong = (int) model.getValueAt(selectedIndex, 0);
        fm_ChiTietDatPhong.SophieuDatPhong = SoPhieuDatPhong;
        fm_ChiTietDatPhong ctdp = new fm_ChiTietDatPhong();
        ctdp.setVisible(true);
    }//GEN-LAST:event_jTable2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btThemMoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel pnChucNang;
    // End of variables declaration//GEN-END:variables
}
