/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;  
/**
 *
 * @author ldlan
 */
public class fm_MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public fm_MainMenu() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        iconmimaxclose = new javax.swing.JPanel();
        btClose = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        btMax = new javax.swing.JPanel();
        Max = new javax.swing.JLabel();
        btMin = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        MenuIcon = new javax.swing.JPanel();
        linehidemenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        buttonhide = new javax.swing.JLabel();
        lineseting = new javax.swing.JPanel();
        seting = new javax.swing.JPanel();
        buttonseting = new javax.swing.JLabel();
        Menuhide = new javax.swing.JPanel();
        BtDanhsachPhong = new javax.swing.JPanel();
        buttonDanhsachPhong = new javax.swing.JLabel();
        BtDatPhong = new javax.swing.JPanel();
        buttonDatPhong = new javax.swing.JLabel();
        btQL = new javax.swing.JPanel();
        buttonDatPhong1 = new javax.swing.JLabel();
        PnView = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        Header.setBackground(new java.awt.Color(16, 19, 53));
        Header.setPreferredSize(new java.awt.Dimension(1066, 50));
        Header.setLayout(new java.awt.BorderLayout());

        iconmimaxclose.setBackground(new java.awt.Color(16, 19, 54));
        iconmimaxclose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btClose.setBackground(new java.awt.Color(16, 19, 54));
        btClose.setLayout(new java.awt.BorderLayout());

        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete_32px.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
        });
        btClose.add(Close, java.awt.BorderLayout.CENTER);

        iconmimaxclose.add(btClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, 50));

        btMax.setBackground(new java.awt.Color(16, 19, 54));
        btMax.setLayout(new java.awt.BorderLayout());

        Max.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Max.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/full_screen_32px.png"))); // NOI18N
        Max.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaxMouseExited(evt);
            }
        });
        btMax.add(Max, java.awt.BorderLayout.CENTER);

        iconmimaxclose.add(btMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 50));

        btMin.setBackground(new java.awt.Color(16, 19, 54));
        btMin.setLayout(new java.awt.BorderLayout());
        iconmimaxclose.add(btMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 40, 50));

        Header.add(iconmimaxclose, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(24, 30, 72));
        Menu.setMinimumSize(new java.awt.Dimension(300, 105));
        Menu.setName(""); // NOI18N
        Menu.setPreferredSize(new java.awt.Dimension(300, 865));
        Menu.setLayout(new java.awt.BorderLayout());

        MenuIcon.setBackground(new java.awt.Color(16, 19, 53));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 565));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehidemenu.setBackground(new java.awt.Color(16, 19, 54));
        linehidemenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linehidemenuLayout = new javax.swing.GroupLayout(linehidemenu);
        linehidemenu.setLayout(linehidemenuLayout);
        linehidemenuLayout.setHorizontalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehidemenuLayout.setVerticalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(linehidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        hidemenu.setBackground(new java.awt.Color(16, 19, 54));
        hidemenu.setLayout(new java.awt.BorderLayout());

        buttonhide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/menu_32px.png"))); // NOI18N
        buttonhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhideMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonhideMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonhideMouseExited(evt);
            }
        });
        hidemenu.add(buttonhide, java.awt.BorderLayout.CENTER);

        MenuIcon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 50, 50));

        lineseting.setBackground(new java.awt.Color(16, 19, 54));
        lineseting.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linesetingLayout = new javax.swing.GroupLayout(lineseting);
        lineseting.setLayout(linesetingLayout);
        linesetingLayout.setHorizontalGroup(
            linesetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linesetingLayout.setVerticalGroup(
            linesetingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        MenuIcon.add(lineseting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 50, -1));

        seting.setBackground(new java.awt.Color(16, 19, 54));
        seting.setLayout(new java.awt.BorderLayout());

        buttonseting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonseting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_Logout_40px.png"))); // NOI18N
        buttonseting.setToolTipText("   ");
        buttonseting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsetingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonsetingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonsetingMouseExited(evt);
            }
        });
        seting.add(buttonseting, java.awt.BorderLayout.CENTER);

        MenuIcon.add(seting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 50, 50));

        Menu.add(MenuIcon, java.awt.BorderLayout.LINE_START);

        Menuhide.setBackground(new java.awt.Color(24, 30, 72));
        Menuhide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtDanhsachPhong.setBackground(new java.awt.Color(95, 97, 121));

        buttonDanhsachPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonDanhsachPhong.setForeground(new java.awt.Color(255, 51, 153));
        buttonDanhsachPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDanhsachPhong.setText("Danh Sách Phòng"); // NOI18N
        buttonDanhsachPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDanhsachPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDanhsachPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDanhsachPhongMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtDanhsachPhongLayout = new javax.swing.GroupLayout(BtDanhsachPhong);
        BtDanhsachPhong.setLayout(BtDanhsachPhongLayout);
        BtDanhsachPhongLayout.setHorizontalGroup(
            BtDanhsachPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDanhsachPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        BtDanhsachPhongLayout.setVerticalGroup(
            BtDanhsachPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDanhsachPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        Menuhide.add(BtDanhsachPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 250, -1));

        BtDatPhong.setBackground(new java.awt.Color(95, 97, 121));

        buttonDatPhong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonDatPhong.setForeground(new java.awt.Color(255, 51, 153));
        buttonDatPhong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDatPhong.setText("Đặt Phòng"); // NOI18N
        buttonDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDatPhongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonDatPhongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonDatPhongMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtDatPhongLayout = new javax.swing.GroupLayout(BtDatPhong);
        BtDatPhong.setLayout(BtDatPhongLayout);
        BtDatPhongLayout.setHorizontalGroup(
            BtDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        BtDatPhongLayout.setVerticalGroup(
            BtDatPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDatPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        Menuhide.add(BtDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 250, -1));

        btQL.setBackground(new java.awt.Color(95, 97, 121));

        buttonDatPhong1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonDatPhong1.setForeground(new java.awt.Color(255, 51, 153));
        buttonDatPhong1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonDatPhong1.setText("Đặt Phòng"); // NOI18N
        buttonDatPhong1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDatPhong1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btQLLayout = new javax.swing.GroupLayout(btQL);
        btQL.setLayout(btQLLayout);
        btQLLayout.setHorizontalGroup(
            btQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDatPhong1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        btQLLayout.setVerticalGroup(
            btQLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDatPhong1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        Menuhide.add(btQL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 40));

        Menu.add(Menuhide, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        PnView.setBackground(new java.awt.Color(71, 127, 237));
        PnView.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo (3).png"))); // NOI18N
        jLabel2.setToolTipText("");
        PnView.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(PnView, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1059, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    boolean a = true;
    private JPanel ChildPanl;
    public void changcolor (JPanel hover, Color ran){
        hover.setBackground(ran);
    }
    
    
    public void ClickMenu(JPanel h1, JPanel h2,int muberbool){
        if(muberbool == 1){
            h1.setBackground(new Color(25,29,74));
            h2.setBackground(new Color(5, 10,46));
        }else{
             h2.setBackground(new Color(25,29,74));
            h1.setBackground(new Color(5, 10,46));
        }
    }
    public void changeimage(JLabel Button, String resourcheing){
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourcheing));
        Button.setIcon(aimg);
    }
    
    public void hideShow(JPanel menushowhide, boolean  dashboard, JLabel button){
        
        if(dashboard == true){
            menushowhide.setPreferredSize(new Dimension(50,menushowhide.getHeight()));
            changeimage(button, "/Icon/menu_32px.png");
        }else{
            menushowhide.setPreferredSize(new Dimension(300,menushowhide.getHeight()));
            changeimage(button, "/Icon/back_32px.png");

        }
    }
    
    public void showPanel(JPanel panel){
        ChildPanl = panel;
        PnView.removeAll();
        PnView.add(ChildPanl);
        PnView.validate();
    }
    // <editor-fold defaultstate="collapsed" desc="Event">       
    

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        System.exit(0);

    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        changcolor(btClose, new Color(25, 29, 74));
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        changcolor(btClose, new Color(5, 10, 46));
    }//GEN-LAST:event_CloseMouseExited

    private void MaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxMouseClicked
        if(this.getExtendedState() != fm_MainMenu.MAXIMIZED_BOTH){
            this.setExtendedState(fm_MainMenu.MAXIMIZED_BOTH);
        }else{
            this.setExtendedState(NORMAL);

        }
    }//GEN-LAST:event_MaxMouseClicked

    private void MaxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxMouseEntered
        changcolor(btMax, new Color(25, 29, 74));
    }//GEN-LAST:event_MaxMouseEntered

    private void MaxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxMouseExited
        changcolor(btMax, new Color(5, 10, 46));
    }//GEN-LAST:event_MaxMouseExited

    private void buttonhideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhideMouseClicked
        ClickMenu(hidemenu, seting, 1);

        if( a == true){
            hideShow(Menu, a,buttonhide);
            SwingUtilities.updateComponentTreeUI(this);
            a= false;
        }else{
            hideShow(Menu, a,buttonhide);
            SwingUtilities.updateComponentTreeUI(this);
            a= true;
        }

    }//GEN-LAST:event_buttonhideMouseClicked

    private void buttonhideMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhideMouseEntered
        changcolor(linehidemenu, new Color(247, 78, 105));
    }//GEN-LAST:event_buttonhideMouseEntered

    private void buttonhideMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhideMouseExited
        changcolor(linehidemenu, new Color(5, 10, 46));
    }//GEN-LAST:event_buttonhideMouseExited

    private void buttonsetingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsetingMouseClicked
        ClickMenu(seting, hidemenu, 1);
    }//GEN-LAST:event_buttonsetingMouseClicked

    private void buttonsetingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsetingMouseEntered
        changcolor(lineseting, new Color(8, 177, 150));
    }//GEN-LAST:event_buttonsetingMouseEntered

    private void buttonsetingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsetingMouseExited
        changcolor(lineseting, new Color(5, 10, 46));
    }//GEN-LAST:event_buttonsetingMouseExited

    private void buttonDanhsachPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDanhsachPhongMouseClicked
        showPanel(new fm_DanhSachPhong());
        if( a == true){
            hideShow(Menu, a,buttonhide);
            SwingUtilities.updateComponentTreeUI(this);
            a= false;
        }else{
            hideShow(Menu, a,buttonhide);
            SwingUtilities.updateComponentTreeUI(this);
            a= true;
        }

    }//GEN-LAST:event_buttonDanhsachPhongMouseClicked

    private void buttonDanhsachPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDanhsachPhongMouseEntered
        changcolor(BtDanhsachPhong, new Color(8, 177, 150));
    }//GEN-LAST:event_buttonDanhsachPhongMouseEntered

    private void buttonDanhsachPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDanhsachPhongMouseExited
        changcolor(BtDanhsachPhong, new Color(95,97,121));
    }//GEN-LAST:event_buttonDanhsachPhongMouseExited

    private void buttonDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDatPhongMouseClicked
        showPanel(new fm_DatPhong());
        if( a == true){
            hideShow(Menu, a,buttonhide);
            SwingUtilities.updateComponentTreeUI(this);
            a= false;
        }else{
            hideShow(Menu, a,buttonhide);
            SwingUtilities.updateComponentTreeUI(this);
            a= true;
        }

    }//GEN-LAST:event_buttonDatPhongMouseClicked

    private void buttonDatPhongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDatPhongMouseEntered
        changcolor(BtDatPhong, new Color(8, 177, 150));
    }//GEN-LAST:event_buttonDatPhongMouseEntered

    private void buttonDatPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDatPhongMouseExited
        changcolor(BtDatPhong, new Color(95,97,121));
    }//GEN-LAST:event_buttonDatPhongMouseExited

    private void buttonDatPhong1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDatPhong1MouseClicked
        showPanel(new pn_DichVu());
    }//GEN-LAST:event_buttonDatPhong1MouseClicked
// </editor-fold>  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fm_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fm_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fm_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fm_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new fm_MainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtDanhsachPhong;
    private javax.swing.JPanel BtDatPhong;
    private javax.swing.JLabel Close;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Max;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JPanel Menuhide;
    private javax.swing.JPanel PnView;
    private javax.swing.JPanel btClose;
    private javax.swing.JPanel btMax;
    private javax.swing.JPanel btMin;
    private javax.swing.JPanel btQL;
    private javax.swing.JLabel buttonDanhsachPhong;
    private javax.swing.JLabel buttonDatPhong;
    private javax.swing.JLabel buttonDatPhong1;
    private javax.swing.JLabel buttonhide;
    private javax.swing.JLabel buttonseting;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JPanel iconmimaxclose;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel linehidemenu;
    private javax.swing.JPanel lineseting;
    private javax.swing.JPanel seting;
    // End of variables declaration//GEN-END:variables
}
