<?xml version="1.0" encoding="utf-8"?><Database Name="WebKhachSan" Class="MyDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HUY\SQLEXPRESS;Initial Catalog=WebKhachSan;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebKhachSanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AnhPhong" Member="AnhPhongs">
    <Type Name="AnhPhong">
      <Column Name="IDAnhPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Phong_AnhPhong" Member="Phong" ThisKey="MaPhong" OtherKey="MaPhong" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietTienNghi" Member="ChiTietTienNghis">
    <Type Name="ChiTietTienNghi">
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDTN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Phong_ChiTietTienNghi" Member="Phong" ThisKey="MaPhong" OtherKey="MaPhong" Type="Phong" IsForeignKey="true" />
      <Association Name="TienNghi_ChiTietTienNghi" Member="TienNghi" ThisKey="IDTN" OtherKey="IDTN" Type="TienNghi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TinhTrang" Member="TinhTrangs">
    <Type Name="TinhTrang">
      <Column Name="IDTinhTrang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maTinhTrang" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenTinhTrang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TinhTrang_TaiKhoan" Member="TaiKhoans" ThisKey="maTinhTrang" OtherKey="maTinhTrang" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="IDHoaDon" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayThue" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Phong_HoaDon" Member="Phong" ThisKey="MaPhong" OtherKey="MaPhong" Type="Phong" IsForeignKey="true" />
      <Association Name="TaiKhoan_HoaDon" Member="TaiKhoan" ThisKey="IDTaiKhoan" OtherKey="IDTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhuVuc" Member="KhuVucs">
    <Type Name="KhuVuc">
      <Column Name="IDKhuVuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuongPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AnhDaiDien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="anhduphong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="KhuVuc_Phong" Member="Phongs" ThisKey="IDKhuVuc" OtherKey="IDKhuVuc" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.KieuPhong" Member="KieuPhongs">
    <Type Name="KieuPhong">
      <Column Name="IDKieuPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKieuPhong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KieuPhong_Phong" Member="Phongs" ThisKey="IDKieuPhong" OtherKey="IDKieuPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="IDLoaiPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiPhong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoLuongPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnhDaiDien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="IDLoaiPhong" OtherKey="IDLoaiPhong" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="MaPhong" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GiaPhong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IDKhuVuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDLoaiPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnhDaiDien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Vitri" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IDKieuPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="Phong_AnhPhong" Member="AnhPhongs" ThisKey="MaPhong" OtherKey="MaPhong" Type="AnhPhong" />
      <Association Name="Phong_ChiTietTienNghi" Member="ChiTietTienNghis" ThisKey="MaPhong" OtherKey="MaPhong" Type="ChiTietTienNghi" />
      <Association Name="Phong_HoaDon" Member="HoaDons" ThisKey="MaPhong" OtherKey="MaPhong" Type="HoaDon" />
      <Association Name="KhuVuc_Phong" Member="KhuVuc" ThisKey="IDKhuVuc" OtherKey="IDKhuVuc" Type="KhuVuc" IsForeignKey="true" />
      <Association Name="KieuPhong_Phong" Member="KieuPhong" ThisKey="IDKieuPhong" OtherKey="IDKieuPhong" Type="KieuPhong" IsForeignKey="true" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="IDLoaiPhong" OtherKey="IDLoaiPhong" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResetPass" Member="ResetPasses">
    <Type Name="ResetPass">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="maRS" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="ID_NguoiDung" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiHan" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="TaiKhoan_ResetPass" Member="TaiKhoan" ThisKey="ID_NguoiDung" OtherKey="IDTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="IDTaiKhoan" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(13)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="maTinhTrang" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="TaiKhoan_HoaDon" Member="HoaDons" ThisKey="IDTaiKhoan" OtherKey="IDTaiKhoan" Type="HoaDon" />
      <Association Name="TaiKhoan_ResetPass" Member="ResetPasses" ThisKey="IDTaiKhoan" OtherKey="ID_NguoiDung" Type="ResetPass" />
      <Association Name="TinhTrang_TaiKhoan" Member="TinhTrang" ThisKey="maTinhTrang" OtherKey="maTinhTrang" Type="TinhTrang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TienNghi" Member="TienNghis">
    <Type Name="TienNghi">
      <Column Name="IDTN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AnhDaiDien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TienNghi_ChiTietTienNghi" Member="ChiTietTienNghis" ThisKey="IDTN" OtherKey="IDTN" Type="ChiTietTienNghi" />
    </Type>
  </Table>
</Database>